export enum ErrorCode {
  // --- Auth ---
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_REFRESH_TOKEN = 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_EXPIRED = 'REFRESH_TOKEN_EXPIRED',
  REFRESH_TOKEN_REUSE = 'REFRESH_TOKEN_REUSE',
  REFRESH_TOKEN_USED = 'REFRESH_TOKEN_USED',
  NO_REFRESH_TOKEN = 'NO_REFRESH_TOKEN',
  MISSING_CSRF_TOKEN = 'MISSING_CSRF_TOKEN',
  INVALID_CSRF_TOKEN = 'INVALID_CSRF_TOKEN',
  UNAUTHORIZED = 'UNAUTHORIZED',

  // --- Users ---
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  EMAIL_TAKEN = 'EMAIL_TAKEN',
  USERNAME_TAKEN = 'USERNAME_TAKEN',

  // --- Events ---
  EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
  EVENT_CANCELLED = 'EVENT_CANCELLED',
  EVENT_ENDED = 'EVENT_ENDED',
  EVENT_START_IN_PAST = 'EVENT_START_IN_PAST',
  EVENT_STATUS_NOT_ALLOWED = 'EVENT_STATUS_NOT_ALLOWED',
  INVALID_STATUS_TRANSITION = 'INVALID_STATUS_TRANSITION',
  REGISTRATION_CLOSED = 'REGISTRATION_CLOSED',
  NO_FILE_PROVIDED = 'NO_FILE_PROVIDED',

  // --- Attendance ---
  ALREADY_REGISTERED = 'ALREADY_REGISTERED',
  NOT_REGISTERED = 'NOT_REGISTERED',
  ATTENDEE_NOT_FOUND = 'ATTENDEE_NOT_FOUND',
  ATTENDEE_ALREADY_REMOVED = 'ATTENDEE_ALREADY_REMOVED',
  CAPACITY_FULL = 'CAPACITY_FULL',
  NOT_ATTENDING = 'NOT_ATTENDING',
  GUESTS_NOT_ALLOWED = 'GUESTS_NOT_ALLOWED',
  GUEST_NAME_REQUIRED = 'GUEST_NAME_REQUIRED',
  ACCOUNT_REQUIRED = 'ACCOUNT_REQUIRED',
  NO_IDENTITY_PROVIDED = 'NO_IDENTITY_PROVIDED',

  // --- Invite Links ---
  INVITE_LINK_NOT_FOUND = 'INVITE_LINK_NOT_FOUND',
  INVITE_LINK_INVALID = 'INVITE_LINK_INVALID',
  INVITE_LINK_EXPIRED = 'INVITE_LINK_EXPIRED',
  INVITE_LINK_EXHAUSTED = 'INVITE_LINK_EXHAUSTED',
  INVITE_TOKEN_REQUIRED = 'INVITE_TOKEN_REQUIRED',

  // --- Whitelist ---
  NOT_INVITED = 'NOT_INVITED',
  ALREADY_ON_WHITELIST = 'ALREADY_ON_WHITELIST',
  WHITELIST_ENTRY_NOT_FOUND = 'WHITELIST_ENTRY_NOT_FOUND',

  // --- Prizes ---
  PRIZE_NOT_FOUND = 'PRIZE_NOT_FOUND',
  WINNER_ALREADY_ASSIGNED = 'WINNER_ALREADY_ASSIGNED',
  NO_ATTENDEES = 'NO_ATTENDEES',

  // --- Media ---
  MEDIA_NOT_FOUND = 'MEDIA_NOT_FOUND',
  FILE_TOO_LARGE = 'FILE_TOO_LARGE',

  // --- Chat ---
  CHAT_NOT_AVAILABLE = 'CHAT_NOT_AVAILABLE',

  // --- Generic ---
  FORBIDDEN = 'FORBIDDEN',
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
